/*****************************************************************************************************************
NAME:    Wisdom Etta
PURPOSE:solving multiple complexity questions using SQL

MODIFICATION LOG:
Ver      Date        Author        Description
-----   ----------   -----------   -------------------------------------------------------------------------------
1.0     05/23/2022   JJAUSSI       1. Built this script for EC IT440


RUNTIME: 
Xm Xs

NOTES: 
craft answers using SQL to the questions generated by students 
using tools...
-Adventure meta data - https://dataedo.com/samples/html/AdventureWorks/index.html
-SQL
-SSMS
 
******************************************************************************************************************/

-- Q1: What is the total number of products in the Product table? by Denis Mugoya
-- A1: The answer is 504

SELECT COUNT(*) AS totalProduct
FROM Production.Product;

SELECT GETDATE() AS my_date; 

--Q2:What is the average of new people hired by the company per year? by Midjerry Alphonse
--A1: The answer is 36
SELECT 
    AVG
	(HireCount)
	AS 
	AvgHiresPerYear
   FROM (SELECT 
        YEAR(HireDate) 
		AS HireYear, 
        COUNT(*) 
		AS HireCount
    FROM 
        HumanResources.Employee
    GROUP BY 
        YEAR(HireDate)
     ) AS 
        yearhires;

--Q3: Based on the hire date, which top five employees have been hired for the longest period? by Catherine Kivindu
--A3:found in the code

SELECT 
    TOP 5 
    BusinessEntityID
	,JobTitle
	,HireDate
   FROM 
    HumanResources.Employee
   ORDER BY 
    HireDate 
	ASC;

--Q4:I want to know which items are making us the most money, can you show me profit margins for each product? by Ethan Silva
--A1:Run code for Answer
   SELECT 
         p.Name 
	AS Product,
         p.ProductID,
    SUM(sod.LineTotal) 
	AS 
	     TSales,
    SUM(sod.OrderQty * pch.StandardCost)
	AS 
	     TCost,
         (SUM(sod.LineTotal) - SUM(sod.OrderQty * pch.StandardCost)) / SUM(sod.LineTotal) * 100 
	AS 
	     ProfitMargin
    FROM 
         Production.Product p
    JOIN 
         Sales.SalesOrderDetail sod ON p.ProductID = sod.ProductID
    JOIN 
         Production.ProductCostHistory pch ON p.ProductID = pch.ProductID
    GROUP BY 
         p.Name, p.ProductID
    ORDER BY 
         ProfitMargin 
	DESC;

	/***Q5: show the monthly sales trends for the last year 
	broken down by product category and highlight any significant changes in sales pattern. by Wisdom Etta (me)
	****/
	--A5: Run code and check client statistics

	select 
       YEAR
	   (soh.OrderDate)
	 as 
	   Year,
       MONTH
	   (soh.OrderDate) 
	 as
	   Month,
       pc.Name 
	 as
	   ProductCategory,
    SUM
	   (sod.LineTotal) 
	 as 
	    TSales
    from 
        Sales.SalesOrderHeader soh
    inner join 
        Sales.SalesOrderDetail sod on soh.SalesOrderID = sod.SalesOrderID
    inner join
        Production.Product p on sod.ProductID = p.ProductID
    inner join 
        Production.ProductSubcategory psc on p.ProductSubcategoryID = psc.ProductSubcategoryID
    inner join
        Production.ProductCategory pc on psc.ProductCategoryID = pc.ProductCategoryID
    where 
        soh.OrderDate >= DATEADD(YEAR, -1, GETDATE())
    group by
         YEAR
	     (soh.OrderDate), 
		 MONTH(soh.OrderDate),
		 pc.Name
   order by
         Year, Month,
		 ProductCategory;

/****Q6:As a production manager, I need a report on the average production
time for each product category over the past five years. Use the Production.WorkOrder 
and Production.ProductCategory tables. By Mwanga Benamoyo Isaac
*****/
--A6:check client stats
   select 
       pc.Name as ProductCAT,
    AVG(DATEDIFF(day, wo.StartDate, wo.EndDate)) as AvgProductionTime
   from 
      Production.WorkOrder wo
   inner join
      Production.Product p ON wo.ProductID = p.ProductID
inner join
      Production.ProductSubcategory psc ON p.ProductSubcategoryID = psc.ProductSubcategoryID
inner join 
      Production.ProductCategory pc ON psc.ProductCategoryID = pc.ProductCategoryID
 where 
     wo.StartDate >= DATEADD(YEAR, -5, GETDATE())
 group by
    pc.Name
order by
    AvgProductionTime DESC;
--Q7:How can you retrieve a list of all tables and their row counts in the database by Wisdom Etta (ME)
--A7:run code and see answer
  select 
      SCHEMA_NAME(t.schema_id) AS SchemaName,
      t.name 
	as
	   TableName,
    SUM(p.rows) AS Rows
    from
      sys.tables t
    join 
       sys.partitions p ON t.object_id = p.object_id
    where 
       p.index_id IN (0, 1) 
   group by    SCHEMA_NAME(t.schema_id), t.name
   order by
    Rows DESC, TableName;

--Q8:Can you list the views in the Sales schema that contain customer demographic data by Edmund Nettey Ababio
--A8:check code

  select 
    TABLE_SCHEMA, 
    TABLE_NAME
  from
      INFORMATION_SCHEMA.VIEWS
  where
       TABLE_SCHEMA = 'Sales' 
    AND 
	   (TABLE_NAME = 'vPersonDemographics' OR TABLE_NAME = 'vStoreWithDemographics');
